/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2022-09-25 04:00:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("    <link rel=\"icon\" href=\"images/MainLogo.png\" type=\"image/gif\" sizes=\"16x16\">\n");
      out.write("    <title>MayCome</title>\n");
      out.write("        <script  src=\"lib/jquery-3.5.1.min.js\"></script>\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta name=\"mobile-web-app-capable\" content=\"yes\">\n");
      out.write("        <style>\n");
      out.write("            @font-face {\n");
      out.write("               font-family: menuFont;\n");
      out.write("               src: url(fonts/BalsamiqSans-Regular.ttf);\n");
      out.write("            }\n");
      out.write("            .custom-file-upload {\n");
      out.write("            \t\t    border: 1px solid #ccc;\n");
      out.write("            \t\t    border-radius:10px;\n");
      out.write("            \t\t    display: inline-block;\n");
      out.write("            \t\t    padding: 5px 10px;\n");
      out.write("            \t\t    cursor: pointer;\n");
      out.write("            \t\t    background-color: #005194;\n");
      out.write("            \t\t    color:white;\n");
      out.write("            \t\t    width:auto;\n");
      out.write("            \t\t}\n");
      out.write("\n");
      out.write("            #dirArea::after{\n");
      out.write("                flex: auto;\n");
      out.write("                content:\"\";\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            .center {\n");
      out.write("              display: block;\n");
      out.write("              margin-left: auto;\n");
      out.write("              margin-right: auto;\n");
      out.write("            }\n");
      out.write("            .filFolders{\n");
      out.write("                width:99%;\n");
      out.write("                height:40%;\n");
      out.write("                padding:1px;\n");
      out.write("                color:black;\n");
      out.write("                font-size:11px;\n");
      out.write("                text-align: center;\n");
      out.write("                overflow-y:scroll;\n");
      out.write("                word-wrap:break-word;\n");
      out.write("                overflow:none;\n");
      out.write("                font-family: Verdana;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .fileContainer{\n");
      out.write("                width:80px;\n");
      out.write("                height:100px;\n");
      out.write("                display:inline-block;\n");
      out.write("                margin:1px;\n");
      out.write("                padding:2px;\n");
      out.write("            }\n");
      out.write("            .filFolders::-webkit-scrollbar {\n");
      out.write("                         display: none;\n");
      out.write("                     }\n");
      out.write("            #addressbar::-webkit-scrollbar {\n");
      out.write("               display: none;\n");
      out.write("           }\n");
      out.write("           img{\n");
      out.write("            max-width:80%;\n");
      out.write("            max-height:80%;\n");
      out.write("           }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body style=\"margin:0px\">\n");
      out.write("\n");
      out.write("    <img id=\"loadingGif\" src=\"images/LOADING.gif\"  style=\"width:200px;display: none;top:-12;left:0;right:0;margin-right:auto;margin-left: auto;position:absolute;margin-right: auto;z-index:1\">\n");
      out.write("    <div id=\"newFolder\"style=\"display:none;width:80%;height:11%;border:1px solid white;border-top-right-radius:20px;border-bottom-left-radius:20px;background-color:#005194;left:0;right:0;top:0;bottom:0;margin: auto;position:absolute;margin-right: auto;z-index:1;padding:15px\">\n");
      out.write("        <input id=\"newFname\" type=\"text\" style=\"width:100%;height:30px;border-radius:20px;border:1px solid #005194;padding:5px\">\n");
      out.write("        <button onclick=\"closeNewF()\" class=\"custom-file-upload\" style=\"left:0;right:0;margin-left:auto;margin-right:auto;font-family:Avenir;font-size:100%;margin-top:10px;font-size:12px\">X</button>\n");
      out.write("        <button onclick=\"createF()\" class=\"custom-file-upload\" style=\"left:0;right:0;margin-left:auto;margin-right:auto;font-family:Avenir;font-size:100%;margin-top:10px;font-size:12px;float:right\">Create</button>\n");
      out.write("    </div>\n");
      out.write("        <div style=\"width:100%;overflow:hidden;margin:0px;background-color:#d3e5f5;height:100%\">\n");
      out.write("\n");
      out.write("            <div style=\"background-color:#005194;margin:0px;width:100%;\">\n");
      out.write("                <img width=\"25px\" src=\"images/MainLogo.png\"><h2 style=\"display:inline;padding:1%;font-family:menuFont;color:whitesmoke;margin:0px;letter-spacing:2px;font-size:100%\">MayCome</h2>\n");
      out.write("            </div>\n");
      out.write("            <button class=\"custom-file-upload\" style=\"margin:10px;margin-bottom:0px;margin-top:5px;font-family:Avenir;font-size:100%;float:right;\" onclick=\"back()\"><img width=\"20px\" src=\"images/Back.png\"></button>\n");
      out.write("            <button class=\"custom-file-upload\" style=\"margin:10px;margin-right:0px;margin-bottom:0px;margin-top:5px;font-family:Avenir;font-size:100%;float:right;\" onclick=\"newf()\"><img width=\"20px\" src=\"images/newFolder.png\"></button>\n");
      out.write("            <label class=\"custom-file-upload \" style=\"margin:10px;margin-bottom:0px;margin-top:5px;font-family:Avenir;\"><img width=\"20px\" src=\"images/Upload.png\">\n");
      out.write("                <input type=\"file\" onchange=\"fileLoad()\" id=\"data\" name=\"data\" style=\"border-radius:10px;text-align: center;display:none\" multiple/>\n");
      out.write("            </label>\n");
      out.write("            <div id=\"uploadfiles\" style=\"display:none;\">\n");
      out.write("            <h5 id=\"filesInfo\" style=\"display:inline;font-family:Verdana;font-weight:normal;color:#00335c\"></h5>\n");
      out.write("            <button class=\"custom-file-upload\" style=\"margin:10px;margin-bottom:0px;margin-top:5px;font-family:Avenir;font-size:100%;\" onclick=\"upload()\">Upload</button>\n");
      out.write("            <div id=\"percent\" style=\"background-color:#078adb;width:0%;height:10px;margin-top:5px\">\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div id=\"addressbar\" style=\"margin:10px;background-color:#005194;border:1px solid #005694;border-radius:5px;padding:3px;padding-left:5px;color:whitesmoke;font-size:13px;overflow-x:scroll;white-space:nowrap;font-family:Verdana\">\n");
      out.write("            </div>\n");
      out.write("            <div id=\"dirAreaMain\" style=\"background-color:#edf8ff;border:1px solid #005694;border-radius:5px;height:77vh;margin:10px;overflow-y:scroll;\">\n");
      out.write("                <div id=\"dirArea\" style=\"display:flex;flex-wrap:wrap;justify-content:space-between\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            var dirs;\n");
      out.write("            var currDir;\n");
      out.write("            var filesCount;\n");
      out.write("            getDirectories('');\n");
      out.write("            document.getElementById(\"loadingGif\").style.display=\"block\";\n");
      out.write("\n");
      out.write("            function back(){\n");
      out.write("                 getDirectories(currDir.substring(0,currDir.lastIndexOf(\"/\")))\n");
      out.write("            }\n");
      out.write("            function newf(){\n");
      out.write("                document.getElementById(\"newFolder\").style.display=\"block\";\n");
      out.write("            }\n");
      out.write("            function closeNewF(){\n");
      out.write("                document.getElementById(\"newFolder\").style.display=\"none\";\n");
      out.write("            }\n");
      out.write("            function fileLoad(){\n");
      out.write("                filesCount=document.getElementById(\"data\").files.length;\n");
      out.write("                document.getElementById(\"filesInfo\").innerHTML=+filesCount+((filesCount==1)? ' file':' files')+\" ready for Upload\"\n");
      out.write("                document.getElementById(\"uploadfiles\").style.display=\"inline\";\n");
      out.write("            }\n");
      out.write("            function folderClick(index){\n");
      out.write("                getDirectories(currDir+'/'+dirs.folders[index]);\n");
      out.write("            }\n");
      out.write("            function filesClick(index){\n");
      out.write("              window.open(window.location.origin+window.location.pathname+'/megam/files/'+currDir+'/'+dirs.files[index],\"_blank\");\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function createF(){\n");
      out.write("                var fName=document.getElementById(\"newFname\").value\n");
      out.write("                if(fName==\"\"){\n");
      out.write("                    alert(\"Invalid Name\")\n");
      out.write("                }\n");
      out.write("                else{\n");
      out.write("                    $.ajax({\n");
      out.write("                            url:window.location.origin+window.location.pathname+'/megam/newDirectory?password=sanju@1398',\n");
      out.write("                            type:'post',\n");
      out.write("                            data:'filePath='+currDir.replace('&','%26')+'/'+fName,\n");
      out.write("                            success:function(response){\n");
      out.write("                                alert(response);\n");
      out.write("                                document.getElementById(\"newFolder\").style.display=\"none\";\n");
      out.write("                                getDirectories(currDir);\n");
      out.write("                            },\n");
      out.write("                             error:function(response){\n");
      out.write("                                 alert(response);\n");
      out.write("                                 document.getElementById(\"loadingGif\").style.display=\"none\";\n");
      out.write("                                 document.getElementById(\"newFolder\").style.display=\"none\";\n");
      out.write("                             }\n");
      out.write("                         });\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function getDirectories(path){\n");
      out.write("                document.getElementById(\"loadingGif\").style.display=\"block\";\n");
      out.write("                $.ajax({\n");
      out.write("                    url:window.location.origin+window.location.pathname+'/megam/directory?password=sanju@1398',\n");
      out.write("                    type:'post',\n");
      out.write("                    data:'filePath='+path.replace('&','%26'),\n");
      out.write("                    success:function(response){\n");
      out.write("                        dirs=JSON.parse(response);\n");
      out.write("                        dirHtml=\"\";\n");
      out.write("                        for(var i=0;i<dirs.folders.length;i++){\n");
      out.write("                            dirHtml=dirHtml+'<div ondblclick=\"folderClick('+i+')\" class=\"fileContainer\"><img src=\"images/folder.png\" width=70% class=\"center\"><div class=\"filFolders\">'+((dirs.folders[i].length<33) ? dirs.folders[i] : dirs.folders[i].substring(0,33)+'...')+'</div></div>'\n");
      out.write("                            }\n");
      out.write("                        for(var i=0;i<dirs.files.length;i++){\n");
      out.write("                            dirHtml=dirHtml+'<div ondblclick=\"filesClick('+i+')\" class=\"fileContainer\"><div style=\"width:80px;height:60px\"><img src=\"'+window.location.origin+window.location.pathname+'/megam/thumbnail/'+dirs.currDir+'/'+dirs.files[i]+'\" onerror=\"this.onerror=null;this.src=&apos;images/file.png&apos;\" style=\"padding:10px\" class=\"center\"></div><div class=\"filFolders\">'+((dirs.files[i].length<23) ? dirs.files[i] : dirs.files[i].substring(0,20)+'...'+dirs.files[i].substring(dirs.files[i].lastIndexOf('.')-4))+'</div></div>'\n");
      out.write("                        }\n");
      out.write("                        document.getElementById(\"dirArea\").innerHTML=dirHtml;\n");
      out.write("                        document.getElementById(\"dirAreaMain\").scrollTop=0;\n");
      out.write("                        currDir=dirs.currDir;\n");
      out.write("                        document.getElementById(\"addressbar\").innerHTML=currDir;\n");
      out.write("                        document.getElementById(\"loadingGif\").style.display=\"none\";\n");
      out.write("                    },\n");
      out.write("                     error:function(response){\n");
      out.write("                         alert(response);\n");
      out.write("                         document.getElementById(\"loadingGif\").style.display=\"none\";\n");
      out.write("                     }\n");
      out.write("             });\n");
      out.write("            }\n");
      out.write("        function gett(){\n");
      out.write("            $.ajax({\n");
      out.write("                    url:window.location.origin+window.location.pathname+'/megam/murugar01',\n");
      out.write("                    type:'get',\n");
      out.write("                    success:function(response){\n");
      out.write("\n");
      out.write("                                        var binaryString = window.atob(response);\n");
      out.write("                                        var binaryLen = binaryString.length;\n");
      out.write("                                        var bytes = new Uint8Array(binaryLen);\n");
      out.write("                                        for (var i = 0; i < binaryLen; i++) {\n");
      out.write("                                           var ascii = binaryString.charCodeAt(i);\n");
      out.write("                                           bytes[i] = ascii;\n");
      out.write("                                        }\n");
      out.write("\n");
      out.write("                                    var blob = new Blob([bytes], {type: \"application/mp3\"});\n");
      out.write("                                    var link = document.getElementById('lin');\n");
      out.write("                                    link.href = window.URL.createObjectURL(blob);\n");
      out.write("                                    var fileName = \"Aathadi_Ammadi.mp3\";\n");
      out.write("                                    link.download = fileName;\n");
      out.write("                    },\n");
      out.write("                    error:function(response){\n");
      out.write("                        alert('An error Occured');\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function upload(){\n");
      out.write("            var formData=new FormData();\n");
      out.write("            for(var i=0;i<filesCount;i++){\n");
      out.write("                formData.append(\"data\",document.getElementById(\"data\").files[i]);\n");
      out.write("            }\n");
      out.write("            formData.append(\"filePath\",currDir.replace('&','%26'))\n");
      out.write("             $.ajax({\n");
      out.write("                xhr: function()\n");
      out.write("                      {\n");
      out.write("                        var xhr = new window.XMLHttpRequest();\n");
      out.write("                        //Upload progress\n");
      out.write("                        xhr.upload.addEventListener(\"progress\", function(evt){\n");
      out.write("                          if (evt.lengthComputable) {\n");
      out.write("                            var percentComplete = evt.loaded / evt.total;\n");
      out.write("                            //Do something with upload progress\n");
      out.write("                            document.getElementById(\"percent\").style.width=percentComplete*100+'%';\n");
      out.write("                          }\n");
      out.write("                        }, false);\n");
      out.write("                        return xhr;\n");
      out.write("                      },\n");
      out.write("                url:window.location.origin+window.location.pathname+'megam/upload?action=upload',\n");
      out.write("                type:'post',\n");
      out.write("                data:formData,\n");
      out.write("                mimeType: \"multipart/form-data\",\n");
      out.write("                processData: false,\n");
      out.write("                contentType: false,\n");
      out.write("                success:function(response){\n");
      out.write("                    alert(\"Files Uploaded\");\n");
      out.write("                    getDirectories(currDir);\n");
      out.write("                    document.getElementById(\"uploadfiles\").style.display=\"none\";\n");
      out.write("                },\n");
      out.write("                error:function(response){\n");
      out.write("                    alert('An error Occured');\n");
      out.write("                    document.getElementById(\"uploadfiles\").style.display=\"none\";\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            }\n");
      out.write("    </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
